name: PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    uses: palasthotel/github-workflows/.github/workflows/wp-plugin-pr.yml@v1
    with:
      slug: process-log
      dev-plugin-name: Process logs - DEV
      required-files: |
        public-functions.php
        uninstall.php
        vendor/autoload.php
        classes/MenuPage.php
        classes/View/ProcessesListTable.php
        classes/View/LogEntriesListTable.php
        css/menu-page.css
        languages/process-log.pot
        languages/process-log-de_DE.mo
